USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS STREAMLIT_APPS;
CREATE SCHEMA IF NOT EXISTS STREAMLIT_APPS.DEV;
CREATE SCHEMA IF NOT EXISTS STREAMLIT_APPS.STAGING;
CREATE SCHEMA IF NOT EXISTS STREAMLIT_APPS.PROD;

CREATE WAREHOUSE IF NOT EXISTS STREAMLIT_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;
