CREATE ROLE IF NOT EXISTS STREAMLIT_ADMIN;
CREATE ROLE IF NOT EXISTS STREAMLIT_DEV;
CREATE ROLE IF NOT EXISTS STREAMLIT_VIEWER;

GRANT ROLE STREAMLIT_VIEWER TO ROLE STREAMLIT_DEV;
GRANT ROLE STREAMLIT_DEV TO ROLE STREAMLIT_ADMIN;
GRANT ROLE STREAMLIT_ADMIN TO ROLE SYSADMIN;
