USE ROLE STREAMLIT_ADMIN;
USE WAREHOUSE STREAMLIT_WH;

CREATE STAGE IF NOT EXISTS STREAMLIT_APPS.PROD.APP_STAGE;

CREATE OR REPLACE STREAMLIT STREAMLIT_APPS.PROD.MY_PORTAL_APP
FROM '@STREAMLIT_APPS.PROD.APP_STAGE'
MAIN_FILE = 'streamlit_app.py'
QUERY_WAREHOUSE = STREAMLIT_WH
TITLE = 'My Business Portal';

ALTER STREAMLIT STREAMLIT_APPS.PROD.MY_PORTAL_APP
ADD LIVE VERSION FROM LAST;

GRANT USAGE ON STREAMLIT STREAMLIT_APPS.PROD.MY_PORTAL_APP
TO ROLE STREAMLIT_VIEWER;
